### ISSUE TITLE
install fails on 1.9.3-p0

### ISSUE THREAD

**Issue by cldwalker** [defunkt/rip#145]
Install doesn't work on 1.9.3:

```
 $ rip install rack-protection
 /Users/bozo/code/fork/rip/lib/rip/helpers.rb:33:in `read': can't convert Fixnum into String (TypeError)
    from /Users/bozo/code/fork/rip/lib/rip/helpers.rb:33:in `read'
    from /Users/bozo/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych.rb:154:in `parse'
    from /Users/bozo/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych.rb:154:in `parse_stream'
    from /Users/bozo/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych.rb:125:in `parse'
    from /Users/bozo/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych.rb:112:in `load'
    from /Users/bozo/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/config_file.rb:239:in `load_file'
    from /Users/bozo/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/config_file.rb:179:in `initialize'
    from /Users/bozo/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems.rb:361:in `new'
    from /Users/bozo/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems.rb:361:in `configuration'
    from /Users/bozo/code/fork/rip/bin/rip-package-handle-gem:19:in `find_gem'
    from /Users/bozo/code/fork/rip/bin/rip-package-handle-gem:34:in `<main>'
```

**Comment by cldwalker** [comment]
Fyi, this happens with rubygems 1.8.10. I also get this on 1.9.2 with rubygems 1.6.2. However ruby 1.8.7 seems to work
